[package]
name = "watchexec-supervisor"
version = "0.1.0"

authors = ["Félix Saparelli <felix@passcod.name>"]
license = "Apache-2.0"
description = "Watchexec's process supervisor component"
keywords = ["process", "command", "supervisor", "watchexec"]

documentation = "https://docs.rs/watchexec-supervisor"
repository = "https://github.com/watchexec/watchexec"
readme = "README.md"

rust-version = "1.58.0"
edition = "2021"

[dependencies]
futures = "0.3.29"
miette = "5.3.0"
thiserror = "1.0.50"
tracing = "0.1.40"

[dependencies.tokio]
version = "1.33.0"
default-features = false
features = ["rt"]

[dependencies.command-group]
version = "3.0.0"
features = ["with-tokio"]

[dev-dependencies.tokio]
version = "1.33.0"
default-features = false
features = ["rt", "macros"]
